---
name: 'Googletest Action'
description: 'GitHub action to build and run Googletest cases'
author: 'Grahame White'
inputs:
  test-path:
    description: 'relative path to directory containing test code'
    required: true
    default: 'tests'
  source-path:
    description: 'relative path to directory containing source code, if different to test path'
    required: false
  parallel-compilation-count:
    description: 'j flag value to pass to make when building unit tests'
    required: true
    default: 'unset'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/apollo-fire/gtest-action:v0.0.6-pre1'
  args:
    - ${{ inputs.test-path }}
    - ${{ inputs.source-path }}
    - ${{ inputs.parallel-compilation-count }}
branding:
  icon: 'code'
  colour: 'orange'
