---
name: Dry run Docker Container Build

on:
  workflow_dispatch:
  merge_group:
  
  pull_request_target:
    branches: ['dependabot/**']

  pull_request:
    types: [opened, synchronize, edited]
    
permissions: read-all

jobs:
  dry-run-docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        
      - name: 'Login to github docker registry'
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Dry Run Build
        id: docker_build
        uses: docker/build-push-action@v6.6.1
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
