---
name: Dry run Docker Container Build

on:
  workflow_dispatch:
  merge_group:

  pull_request:
    types: [opened, synchronize, edited]

permissions: {}

jobs:
  dry-run-docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Dry Run Build
        id: docker_build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          load: true
          tags: local/gtest-action:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: GTest Action without existing CMake file
        run: |
          docker run --pull=never --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w /github/workspace \
            local/gtest-action:test \
            "test/working_unittest_project" "" "unset" "0"

      - name: Clean workspace after test
        run: sudo git clean -ffdx test/working_unittest_project/

      - name: GTest Action with existing CMake file
        run: |
          docker run --pull=never --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w /github/workspace \
            local/gtest-action:test \
            "test/working_unittest_project_with_existing_cmake" "" "unset" "0"

      - name: GTest Action with mix of project styles, with and without existing CMake file
        run: |
          docker run --pull=never --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w /github/workspace \
            local/gtest-action:test \
            "test/working_unittest_project;test/working_unittest_project_with_existing_cmake" "" "unset" "0"

      - name: Clean workspace after mixed test
        run: sudo git clean -ffdx test/working_unittest_project/

      - name: GTest Action building with j8 flag set
        run: |
          docker run --pull=never --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w /github/workspace \
            local/gtest-action:test \
            "test/working_unittest_project" "" "8" "0"

      - name: GTest Action shuffle 10 times
        run: |
          docker run --pull=never --rm \
            -v "$GITHUB_WORKSPACE:/github/workspace" \
            -w /github/workspace \
            local/gtest-action:test \
            "test/working_unittest_project" "" "unset" "10"

      - name: Run test scenarios for passing/failing tests
        uses: ./.github/actions/test-scenarios
        with:
          execution-mode: docker
          docker-image: local/gtest-action:test
