---
name: Lint Project

on:
  merge_group:

  push:
    branches:
      - main

  pull_request_target:
    branches: ["dependabot/**"]

  pull_request:
    types: [opened, synchronize, edited]

permissions: read-all

jobs:
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        with:
          # Get all history to be able to identify changed files
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v7.1.0
        env:
          # only log identified linting issues
          LOG_LEVEL: NOTICE
          # Only lint new and modified files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable cpplint as it conflicts with clang-format
          VALIDATE_CPP: false
