---
name: Lint Project

on:
  merge_group:

  push:
    branches:
      - main

  pull_request_target:
    branches: ["dependabot/**"]

  pull_request:
    types: [opened, synchronize, edited]

permissions: {}

jobs:
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write
      pull-requests: write

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Get all history to be able to identify changed files
          fetch-depth: 0
          persist-credentials: false

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          # only log identified linting issues
          LOG_LEVEL: NOTICE
          # Only lint new and modified files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable cpplint as it conflicts with clang-format
          VALIDATE_CPP: false
