---
name: Test detection of passing / failing unit tests

on:
  merge_group:

  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, edited]

permissions: read-all

jobs:
  test-passing-failing-tests:
    runs-on: ubuntu-latest
    name: Test Detection Of Passing / Failing Tests
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Gtest
        run: |
          sudo apt-get install libgtest-dev gcovr libicu-dev valgrind
          pushd /usr/src/gtest || exit 1
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp /usr/src/googletest/googletest/lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
          popd || exit 2

      - name: Run test scenarios
        uses: ./.github/actions/test-scenarios
        with:
          execution-mode: direct
