---
name: Test released GoogleTest action

on:
  workflow_dispatch:
  
jobs:
  test_ccs_build:
    runs-on: ubuntu-latest
    name: Test GTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: GTest Action
        uses: apollo-fire/gtest-action@v0.0.4
        with:
          test-path: 'test/working_unittest_project'

      - name: GTest Action with existing CMake file
        uses: apollo-fire/gtest-action@v0.0.4
        with:
          test-path: 'test/working_unittest_project_with_existing_cmake'
